# SPDX-License-Identifier: GPL-2.0

snd-soc-mt8163-objs := mt8163-afe.o mt8163-mclk.o
obj-$(CONFIG_SND_SOC_MT8163) += snd-soc-mt8163.o
obj-$(CONFIG_SND_SOC_MT8163_RADAR_PUFFIN) += snd-soc-mt8163-radar-puffin.o

snd-soc-mt8163-radar-puffin-objs := mt8163-radar-puffin.o
