#!/usr/bin/env bash
# Fail-closed verification of the LibreEcho UI HTTPS/TLS packaging contract.
#
# Two checks are supported and both are executed by the production bundle
# builder:
#   --prefix DIR   the pinned ARM32 mbedTLS prefix that is linked into the UI
#   --binary FILE  a produced or packaged libreecho-web / libreecho-radiod
#
# The verifier never downloads anything and never accepts a dynamic or
# non-ARM32 artifact: a build that silently falls back to src/tls_stub.c (or
# that reports LE_TLS_AVAILABLE=0) must fail here instead of shipping a Web UI
# whose HTTPS toggle can never listen on 8443.
set -euo pipefail

usage() {
  printf '%s\n' 'usage: verify_ui_tls.sh --prefix DIR | --binary FILE [--objects DIR] [--label NAME]'
}

PREFIX=
BINARY=
OBJECTS=
LABEL=
while (($#)); do
  case "$1" in
    --prefix) shift; (($#)) || { usage >&2; exit 2; }; PREFIX=$1 ;;
    --binary) shift; (($#)) || { usage >&2; exit 2; }; BINARY=$1 ;;
    --objects) shift; (($#)) || { usage >&2; exit 2; }; OBJECTS=$1 ;;
    --label) shift; (($#)) || { usage >&2; exit 2; }; LABEL=$1 ;;
    -h|--help) usage; exit 0 ;;
    *) printf 'ERROR: unknown option: %s\n' "$1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done
[[ -n "$PREFIX" || -n "$BINARY" ]] || { usage >&2; exit 2; }
[[ -z "$PREFIX" || -z "$BINARY" ]] || {
  printf 'ERROR: --prefix and --binary are separate checks\n' >&2; exit 2
}

# The pinned dependency this repository packages, resolved relative to this
# script so the check works from any working directory.
SCRIPT_DIR=$(cd -- "$(dirname -- "$0")" && pwd -P)
PINNED_LOCK=$SCRIPT_DIR/../mbedtls/SOURCE.lock

# src/tls.c only string literals.  src/tls_stub.c has none of them, so any of
# them in a packaged binary proves the real implementation was compiled in and
# LE_TLS_AVAILABLE resolved to 1.  The threshold is one, not all three: the
# release link runs with -Wl,--gc-sections, and libreecho-radiod is a TLS
# client that never reaches the self-signed certificate path, so its copy of
# src/tls.c keeps only the layer identity string.  Requiring more would fail a
# correct libreecho-radiod build; requiring none would accept the stub, which
# is why the linked mbedTLS evidence below is a separate hard requirement.
TLS_SOURCE_MARKERS=(
  'libreecho-tls'
  'CN=%s,O=LibreEcho'
  '20200101000000'
)
TLS_SOURCE_MARKER_MIN=1
# Read-only data that only the linked mbedTLS libraries can provide once the
# artifact has been stripped.
MBEDTLS_DATA_MARKERS=(
  '-----BEGIN CERTIFICATE-----'
  'ecdsa_secp256r1_sha256'
  'secp256r1'
)
# Symbols defined by the linked mbedTLS static archives in an unstripped build.
MBEDTLS_SYMBOL_PREFIX=mbedtls_
MBEDTLS_SYMBOL_MIN=50

require_static_arm32() {
  local binary=$1 description
  [[ -f "$binary" && ! -L "$binary" && -s "$binary" ]] || {
    printf 'ERROR: UI TLS artifact is missing or unsafe: %s\n' "$binary" >&2; exit 1
  }
  description=$(file -b "$binary")
  case "$description" in
    *"ELF 32-bit"*"ARM"*"statically linked"*) ;;
    *) printf 'ERROR: UI TLS artifact is not static ARM32: %s: %s\n' \
         "$binary" "$description" >&2; exit 1 ;;
  esac
  if readelf -l "$binary" | grep -q 'Requesting program interpreter'; then
    printf 'ERROR: UI TLS artifact has a dynamic interpreter: %s\n' "$binary" >&2
    exit 1
  fi
  if readelf -d "$binary" 2>/dev/null | grep -q 'NEEDED'; then
    printf 'ERROR: UI TLS artifact has dynamic dependencies: %s\n' "$binary" >&2
    exit 1
  fi
}

count_markers() {
  local text=$1 pattern
  shift
  local count=0
  for pattern in "$@"; do
    if grep -qF -- "$pattern" <<<"$text"; then
      count=$((count + 1))
    fi
  done
  printf '%s' "$count"
}

mbedtls_symbol_count() {
  local binary=$1
  nm --defined-only "$binary" 2>/dev/null |
    awk '{print $NF}' | grep -c "^${MBEDTLS_SYMBOL_PREFIX}" || true
}

json_field() {
  # Read a flat JSON string field.  The lock and provenance records are
  # generated by this repository, so a dependency-free parse is sufficient and
  # a missing field is reported as empty and fails closed at the call site.
  sed -n "s/.*\"$2\": *\"\([^\"]*\)\".*/\1/p" "$1" | head -n 1
}

include_tree_sha256() {
  # Digest the complete include tree exactly the way build_mbedtls.sh records
  # it: sorted relative paths paired with each file's SHA-256, hashed in that
  # order.  Both sides must walk the same tree, so a stale or hand-edited
  # header changes the digest.
  local root=$1 relative
  (
    cd "$root" || exit 1
    find . -type f -print | LC_ALL=C sort | while IFS= read -r path; do
      relative=${path#./}
      printf '%s\0' "$relative"
      sha256sum "$path" | awk '{printf "%s", $1}'
    done
  ) | sha256sum | awk '{print $1}'
}

verify_prefix() {
  local prefix=$1
  [[ -d "$prefix" && ! -L "$prefix" ]] || {
    printf 'ERROR: UI ARM32 mbedTLS prefix is unavailable: %s\n' "$prefix" >&2
    exit 1
  }
  local header
  for header in mbedtls/ssl.h mbedtls/x509_crt.h mbedtls/pk.h mbedtls/entropy.h \
      mbedtls/build_info.h; do
    [[ -f "$prefix/include/$header" && ! -L "$prefix/include/$header" ]] || {
      printf 'ERROR: UI ARM32 mbedTLS prefix is missing %s: %s\n' "$header" "$prefix" >&2
      exit 1
    }
  done
  local version
  version=$(sed -n 's/^#define MBEDTLS_VERSION_STRING  *"\(.*\)"$/\1/p' \
    "$prefix/include/mbedtls/build_info.h" | head -n 1)
  [[ -n "$version" ]] || {
    printf 'ERROR: UI ARM32 mbedTLS prefix has no version string: %s\n' "$prefix" >&2
    exit 1
  }
  local archive members=0
  for archive in libmbedcrypto.a libmbedx509.a libmbedtls.a; do
    [[ -f "$prefix/lib/$archive" && ! -L "$prefix/lib/$archive" ]] || {
      printf 'ERROR: UI ARM32 mbedTLS prefix is missing lib/%s: %s\n' \
        "$archive" "$prefix" >&2
      exit 1
    }
    ar t "$prefix/lib/$archive" 2>/dev/null | grep -q . || {
      printf 'ERROR: UI ARM32 mbedTLS archive is empty: %s/%s\n' "$prefix/lib" "$archive" >&2
      exit 1
    }
    if file -b "$prefix/lib/$archive" | grep -q 'shared object'; then
      printf 'ERROR: UI ARM32 mbedTLS archive is a shared object: %s\n' "$archive" >&2
      exit 1
    fi
    members=$((members + $(ar t "$prefix/lib/$archive" | wc -l)))
  done
  if find "$prefix/lib" -maxdepth 1 -name '*.so*' -print -quit | grep -q .; then
    printf 'ERROR: UI ARM32 mbedTLS prefix contains dynamic libraries: %s\n' "$prefix" >&2
    exit 1
  fi

  # The prefix must be the pinned dependency, not merely an API-compatible
  # build: a stale prefix would link a different version than the one recorded
  # in SOURCE.lock, the license inventory, and the release metadata.
  [[ -f "$PINNED_LOCK" && ! -L "$PINNED_LOCK" ]] || {
    printf 'ERROR: UI ARM32 mbedTLS source lock is unavailable: %s\n' "$PINNED_LOCK" >&2
    exit 1
  }
  local pinned_version pinned_source_sha
  pinned_version=$(json_field "$PINNED_LOCK" version)
  pinned_source_sha=$(json_field "$PINNED_LOCK" source_sha256)
  [[ -n "$pinned_version" && -n "$pinned_source_sha" ]] || {
    printf 'ERROR: UI ARM32 mbedTLS source lock is incomplete: %s\n' "$PINNED_LOCK" >&2
    exit 1
  }
  [[ "$version" == "$pinned_version" ]] || {
    printf 'ERROR: UI ARM32 mbedTLS prefix version %s does not match the pinned %s: %s\n' \
      "$version" "$pinned_version" "$prefix" >&2
    exit 1
  }

  # Cross-check the provenance record the build wrote into the prefix against
  # the lock and against the archives that are about to be linked.
  local source_json=$prefix/mbedtls-source.json
  [[ -f "$source_json" && ! -L "$source_json" ]] || {
    printf 'ERROR: UI ARM32 mbedTLS prefix has no provenance record (mbedtls-source.json): %s\n' \
      "$prefix" >&2
    exit 1
  }
  local recorded_version recorded_source_sha recorded_archive actual
  recorded_version=$(json_field "$source_json" version)
  recorded_source_sha=$(json_field "$source_json" source_archive_sha256)
  [[ "$recorded_version" == "$pinned_version" ]] || {
    printf 'ERROR: mbedTLS provenance version %s does not match the pinned %s: %s\n' \
      "${recorded_version:-missing}" "$pinned_version" "$source_json" >&2
    exit 1
  }
  [[ "$recorded_source_sha" == "$pinned_source_sha" ]] || {
    printf 'ERROR: mbedTLS provenance source archive hash does not match the pin: %s\n' \
      "$source_json" >&2
    exit 1
  }
  for archive in libmbedcrypto.a libmbedx509.a libmbedtls.a; do
    recorded_archive=$(json_field "$source_json" "$archive")
    [[ "$recorded_archive" =~ ^[0-9a-f]{64}$ ]] || {
      printf 'ERROR: mbedtls-source.json records no SHA-256 for %s: %s\n' \
        "$archive" "$source_json" >&2
      exit 1
    }
    actual=$(sha256sum "$prefix/lib/$archive" | awk '{print $1}')
    [[ "$actual" == "$recorded_archive" ]] || {
      printf 'ERROR: UI ARM32 mbedTLS archive does not match its provenance record: %s\n' \
        "$archive" >&2
      exit 1
    }
  done

  # The complete include tree the UI compiles against, not only the version text:
  # a stale or hand-edited header in a cached prefix would otherwise be consumed
  # while the archives still match their recorded digests.
  local recorded_include recorded_tree actual_include actual_tree
  recorded_include=$(json_field "$source_json" include_sha256)
  recorded_tree=$(json_field "$source_json" include_tree_sha256)
  [[ "$recorded_include" =~ ^[0-9a-f]{64}$ && "$recorded_tree" =~ ^[0-9a-f]{64}$ ]] || {
    printf 'ERROR: mbedtls-source.json records no SHA-256 for the include tree: %s\n' \
      "$source_json" >&2
    exit 1
  }
  actual_include=$(sha256sum "$prefix/include/mbedtls/build_info.h" | awk '{print $1}')
  actual_tree=$(include_tree_sha256 "$prefix/include")
  [[ "$actual_include" == "$recorded_include" && "$actual_tree" == "$recorded_tree" ]] || {
    printf 'ERROR: UI ARM32 mbedTLS prefix headers do not match the provenance record: %s\n' \
      "$prefix" >&2
    exit 1
  }
  printf 'ui_tls_prefix=ok mbedtls_version=%s mbedtls_archive_members=%s\n' \
    "$version" "$members"
}

verify_binary() {
  local binary=$1
  local label=${2:-$binary}
  require_static_arm32 "$binary"
  local text source_markers data_markers symbols
  text=$(strings -a "$binary")
  source_markers=$(count_markers "$text" "${TLS_SOURCE_MARKERS[@]}")
  data_markers=$(count_markers "$text" "${MBEDTLS_DATA_MARKERS[@]}")
  symbols=$(mbedtls_symbol_count "$binary")
  ((source_markers >= TLS_SOURCE_MARKER_MIN)) || {
    printf 'ERROR: %s carries no real TLS implementation (src/tls.c markers: %s/%s): %s\n' \
      "$label" "$source_markers" "${#TLS_SOURCE_MARKERS[@]}" "$binary" >&2
    exit 1
  }
  if ((symbols < MBEDTLS_SYMBOL_MIN)) && ((data_markers < 1)); then
    printf 'ERROR: %s has no linked mbedTLS evidence (symbols=%s markers=%s/%s): %s\n' \
      "$label" "$symbols" "$data_markers" "${#MBEDTLS_DATA_MARKERS[@]}" "$binary" >&2
    exit 1
  fi
  if [[ -n "$OBJECTS" ]]; then
    [[ -f "$OBJECTS/tls.o" && ! -L "$OBJECTS/tls.o" ]] || {
      printf 'ERROR: %s did not compile src/tls.c (missing tls.o): %s\n' \
        "$label" "$OBJECTS" >&2
      exit 1
    }
    if [[ -e "$OBJECTS/tls_stub.o" ]]; then
      printf 'ERROR: %s compiled src/tls_stub.c (LE_TLS_AVAILABLE=0): %s\n' \
        "$label" "$OBJECTS" >&2
      exit 1
    fi
  fi
  printf 'ui_tls=%s label=%s static=1 tls_source_markers=%s mbedtls_symbols=%s mbedtls_data_markers=%s\n' \
    'real' "$label" "$source_markers" "$symbols" "$data_markers"
}

[[ -z "$PREFIX" ]] || verify_prefix "$PREFIX"
[[ -z "$BINARY" ]] || verify_binary "$BINARY" "$LABEL"
