/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef __SND_SOC_AMZN_MT8163_SPI_PCM_H
#define __SND_SOC_AMZN_MT8163_SPI_PCM_H

#include "dough.h"

#define AMZN_MT_SPI_PCM		"amzn-mt-spi-pcm"
#define FPGA_FIRMWARE_NAME	"i2s_to_spi_v34.bin"
#define FIRMWARE_MAX_BYTES	(10 * 4096)

#define SPI_SPEED_HZ		50000000
#define SPI_READ_WAIT_MIN_US	6000
#define SPI_READ_WAIT_MAX_US	7000
#define FPGA_DELAY_MS		100
#define PINCTRL_DELAY_MS	100
#define MARGIN_US		500

#define SAMPLING_RATE		16000
#define SPI_N_CHANNELS		DOUGH_AUDIO_NUM_CHANNELS
#define SPI_BYTES_PER_FRAME	(SPI_N_CHANNELS * DOUGH_AUDIO_SAMPLE_WIDTH)
#define SPI_BYTES_PER_PERIOD	(SPI_BYTES_PER_FRAME * \
				 (DOUGH_AUDIO_FRAME_BUF + 1))
#define SPI_N_PERIODS_MIN	1
#define SPI_N_PERIODS_MAX	10
#define SPI_PERIOD_BYTES_MIN	(SPI_BYTES_PER_PERIOD * SPI_N_PERIODS_MIN)
#define SPI_PERIOD_BYTES_MAX	(SPI_BYTES_PER_PERIOD * SPI_N_PERIODS_MAX)
#define SPI_BUFFER_BYTES_MAX	SPI_PERIOD_BYTES_MAX
#define SPI_DMA_BYTES_MAX	(SPI_PERIOD_BYTES_MAX * 2)

#define SPI_SETUP_BUF_SIZE	32
#define MAX_FLUSHED_CYCLES	10

#endif
