/* LibreEcho ARM32 Dropbear server-only, WebUI-backed password-auth build. */
#ifndef LIBREECHO_DROPBEAR_LOCALOPTIONS_H
#define LIBREECHO_DROPBEAR_LOCALOPTIONS_H

#define DROPBEAR_SVR_PASSWORD_AUTH 1
#define DROPBEAR_SVR_PUBKEY_AUTH 0
#define DROPBEAR_SVR_PUBKEY_OPTIONS 0
#define DROPBEAR_CLI_PASSWORD_AUTH 0
#define DROPBEAR_CLI_PUBKEY_AUTH 0

#endif
